version: '3.7'

services:

  frontend:
    image: "crystalcast/frontend:latest"
    user: ${CURRENT_UID}
    restart: on-failure
    ports:
      - "${FRONTEND_PORT}:8000"
    volumes:
      - type: bind
        source: ./frontend-logs
        target: /opt/app/frontend-logs
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 8g

  pygom-wrapper:
    image: "crystalcast/pygom-wrapper:latest"
    user: ${CURRENT_UID}
    ports:
      - "${PYGOM_PORT}:5000"
    environment:
      MPLCONFIGDIR: /usr/src/app
      USERNAME: root
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 4g

  emulation:
    image: "crystalcast/emulation:latest"
    user: ${CURRENT_UID}
    restart: on-failure
    ports:
      - "${EMULATION_PORT}:5001"
    volumes:
      - type: bind
        source: ./emulation_logs
        target: /usr/local/src/myscripts/logs
      - type: bind
        source: ./emulation_config
        target: /usr/local/src/myscripts/config
    deploy:
        resources:
            limits:
              cpus: '0.75'
              memory: 8g

  mongo1:
    image: "crystalcast/mongo:latest"
    user: mongodb:mongodb
    restart: on-failure
    ports:
      - "${MONGODB_PORT}:27017"
    deploy:
        resources:
            limits:
              cpus: '0.25'
              memory: 8g
    volumes:
      - mongodata:/data/db

  mongo-setup:
    image: "crystalcast/mongo-setup:latest"
    user: ${CURRENT_UID}
    depends_on:
      - mongo1
    entrypoint: [ "/home/init.sh" ]

  database-service:
    image: "crystalcast/database-service:latest"
    user: ${CURRENT_UID}
    restart: on-failure
    volumes:
      - type: bind
        source: ./database-service-logs
        target: /opt/app/database-service-logs
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 4g

  # Mongo Express container:
  # Uncomment this section for a graphical user interface for viewing the raw
  # MongoDB data, accessible at http://localhost:8081
  # mongo-express:
  #   image: "mongo-express"
  #   user: ${CURRENT_UID}
  #   restart: on-failure
  #   ports:
  #     - "${MONGOEXPRESS_PORT}:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  #     ME_CONFIG_MONGODB_SERVER: "mongo1"
  #     ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "crystalcast"

volumes:
  mongodata: